env:
  commonjs: true
  es6: true
  node: true
  jest: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {
		indent: ['error', 4],
		semi: ['error', 'always'],
		curly: 0,
		'brace-style': ['error', 'stroustrup'],
		'eol-last': ['error', 'never']
	}
